name: New Challenge
description: Discover new hCaptcha image classification challenges.
title: "[Challenge] "
labels: "\U0001F525 challenge"
body:
  - type: textarea
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: macOS Big Sur
      value: operating system
    validations:
      required: true
